blueprint:
  name: AddOn Surveillance
  description: >-
    Observe if certain Addons are started and provide notifications if not.
    
    
    **IMPORTANT**: This Automation can not detect, weather an AddOn is healthy or not!<br>
    So it might happen, that the Addon has an internal failure, but is running = no report!
    
    
    **Like My Work?** <br>
    [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/I3I4160K4Y)
  domain: automation
  author: Flo-R1der (https://github.com/Flo-R1der)


  input:
    surveillance_mode:
      name: "Surveillance Mode"
      default: exclude
      selector:
        select:
          options:
            - label: Observe all
              value: all
            - label: Exclude Selected
              value: exclude
            - label: Manual Selection
              value: manual
          multiple: false
    exclude_list:
      name: Exclude Selected
      description: '**Only applicable if the "Exclude Selected"-Mode is chosen**'
      default: []
      selector:
        entity:
          integration: hassio
          device_class: running
        multiple: true
    manual_list:
      name: Manual Selection
      description: '**Only applicable if the "Manual Selection"-Mode is chosen**'
      default: []
      selector:
        entity:
          integration: hassio
          device_class: running
        multiple: true
    waiting_minutes:
      name: Trigger Waiting Time
      description: >-
        The time how long the AddOns are allowed to be stopped, before this Automation will be triggered<br>
        **NOTE**: On Startup of Home Assistant it may take some time to detect the "running" state.
      default: 7
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: min
          mode: slider

    custom_conditions:
      name: Custom conditions before taking action
      description: >-
        Optional conditions to check, before the automation should proceed. Can be empty.
      default: []
      selector:
        condition:

    pre_actions:
      name: PRE Actions
      description: >-
        Optional actions to run BEFORE the Notification will be sent. Can be empty.
      default: []
      selector:
        action:
    notification_mode:
      name: "Surveillance Mode"
      description: >-
        **Push to all Devices** uses the `notify.notify`-Service to inform all mobile devices
        
        
        **Push to Selected Devices** requires your selection below
        
        
        **Persistent Notification** will provide a notification in the Home Assistant 
        Side-Bar/Menue. This requires the user to actively look into the App/Web-UI. 
        Will always be provided to all users.
      default: null
      selector:
        select:
          options:
            - label: Push to all Devices
              value: all
            - label: Push to Selected Devices
              value: selected
            - label: Persistent Notification
              value: persistent
            - label: No Notification
              value: none
          multiple: false
    selected_devices:
      name: Selected Devices
      default: []
      selector:
        device:
          integration: mobile_app
        multiple: true

    post_actions:
      name: POST Actions
      description: >-
        Optional actions to run AFTER the Notification was sent. Can be empty.
      default: []
      selector:
        action:


trigger_variables:
  surveillance_mode: !input surveillance_mode
  excluded_entities: !input exclude_list
  manual_list: !input manual_list

  all_running_sensors: "{{ integration_entities('hassio')
    | select('is_state_attr', 'device_class', 'running') | list }}"
  not_running: >-
    {% set not_running = namespace(entities=[], names=[]) -%}
    {% for sensor in all_running_sensors -%}
      {% if is_state(sensor, 'off') -%}
        {% set not_running.entities = not_running.entities + [sensor] -%}
        {% set not_running.names = not_running.names + [device_name(sensor)] -%}
      {% endif -%}
    {% endfor -%}
    {{ not_running }}
  trigger_list: >-
    {% set trigger_list = namespace(entities=[], names=[]) -%}
    {% if surveillance_mode == "all" -%}
      {% set trigger_list = not_running -%}
    {% elif surveillance_mode == "exclude" -%}
      {% for sensor in not_running.entities -%}
        {% if sensor not in excluded_entities -%}
          {% set trigger_list.entities = trigger_list.entities + [sensor] -%}
          {% set trigger_list.names = trigger_list.names + [device_name(sensor)] -%}
        {% endif -%}
      {% endfor -%}
    {% elif surveillance_mode == "manual" -%}
      {% for sensor in not_running.entities -%}
        {% if sensor in manual_list -%}
          {% set trigger_list.entities = trigger_list.entities + [sensor] -%}
          {% set trigger_list.names = trigger_list.names + [device_name(sensor)] -%}
        {% endif -%}
      {% endfor -%}
    {% endif -%}
    {{ trigger_list }}

triggers:
  - trigger: template
    value_template: "{{ trigger_list.entities|count > 0 }}"
    for:
      hours: 0
      minutes: !input waiting_minutes
      seconds: 0


variables:
  notification_mode: !input notification_mode
  selected_devices: !input selected_devices


conditions:
  !input custom_conditions


actions:

